// Package emit renders deterministic, namespace-partitioned Go source.
package emit

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/zzuf/GoWin-AFO/generator/internal/model"
)

type Tree struct {
	Files        map[string][]byte
	ManifestHash string
}

func Render(inv model.Inventory, modulePath string) (Tree, error) {
	t := Tree{Files: map[string][]byte{}, ManifestHash: inv.ManifestHash}
	groups := map[string][]model.Symbol{}
	for _, s := range inv.Symbols {
		if s.SourceType != "project-fixture" && !emittedStatus(s.Status) {
			continue
		}
		groups[s.Namespace] = append(groups[s.Namespace], s)
	}
	namespaces := make([]string, 0, len(groups))
	for ns := range groups {
		namespaces = append(namespaces, ns)
	}
	sort.Strings(namespaces)
	for _, ns := range namespaces {
		symbols := groups[ns]
		sort.Slice(symbols, func(i, j int) bool { return symbols[i].ID < symbols[j].ID })
		dir := "bindings/generated/" + packageDir(ns)
		pkg := packageName(ns)
		header := generatedHeader(inv, symbols)
		files := []struct {
			name   string
			render func(string, []model.Symbol, string) ([]byte, error)
		}{{"ztypes_generated.go", renderTypes}, {"zconstants_generated.go", renderConstants}, {"zcallbacks_generated.go", renderCallbacks}, {"zcom_generated.go", renderCOM}, {"zavailability_windows.go", renderAvailability}, {"zfunctions_windows.go", func(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
			return renderFunctions(pkg, symbols, header, modulePath)
		}}}
		for _, f := range files {
			b, err := f.render(pkg, symbols, header)
			if err != nil {
				return Tree{}, fmt.Errorf("%s/%s: %w", dir, f.name, err)
			}
			t.Files[filepath.ToSlash(filepath.Join(dir, f.name))] = b
		}
		for _, arch := range []string{"386", "amd64", "arm64"} {
			b, err := renderArchTypes(pkg, symbols, header, arch)
			if err != nil {
				return Tree{}, err
			}
			if b != nil {
				t.Files[filepath.ToSlash(filepath.Join(dir, "ztypes_windows_"+arch+".go"))] = b
			}
		}
	}
	bridge, err := renderBridge(inv)
	if err != nil {
		return Tree{}, err
	}
	for k, v := range bridge {
		t.Files[k] = v
	}
	return t, nil
}

func emittedStatus(status model.Status) bool {
	switch status {
	case model.StatusGeneratedPureGo, model.StatusGeneratedAssembly, model.StatusGeneratedCGOBridge,
		model.StatusGeneratedTypeOnly, model.StatusGeneratedManualOverride:
		return true
	default:
		return false
	}
}

func generatedHeader(inv model.Inventory, symbols []model.Symbol) string {
	sources := map[string]string{}
	for _, s := range inv.Sources {
		sources[s.ID] = s.Version
	}
	used := map[string]bool{}
	for _, s := range symbols {
		used[s.SourceID] = true
	}
	ids := make([]string, 0, len(used))
	for id := range used {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	parts := make([]string, 0, len(ids))
	for _, id := range ids {
		parts = append(parts, id+"@"+sources[id])
	}
	return "// Code generated by winapigen " + inv.GeneratorVersion + "; DO NOT EDIT.\n// SPDX-License-Identifier: Apache-2.0\n// Licensing and upstream notices: docs/licensing.md and NOTICE.\n// Inputs: " + strings.Join(parts, ", ") + "\n// Manifest-SHA256: " + inv.ManifestHash + "\n"
}

func renderTypes(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{}
	for _, s := range symbols {
		if s.Architecture != "neutral" || s.Type == nil || s.Kind == model.KindCallback || s.Kind == model.KindCOMInterface {
			continue
		}
		switch s.Kind {
		case model.KindPrimitive, model.KindNativeTypedef, model.KindTypedef, model.KindHandle, model.KindFixedArray:
			renderNamedType(&body, s)
		case model.KindGUID, model.KindStruct:
			if hasBitFields(*s.Type) {
				renderBitField(&body, s)
			} else {
				renderStruct(&body, s)
			}
		case model.KindUnion:
			if len(s.Type.Layouts) > 1 {
				continue
			}
			imports["unsafe"] = true
			renderUnion(&body, s, "")
		case model.KindFlexibleArray:
			imports["fmt"] = true
			imports["unsafe"] = true
			renderFlexible(&body, s)
		case model.KindRuntimeClass:
			fmt.Fprintf(&body, "// %s identifies the WinRT runtime class %s.\ntype %s struct{}\n\nconst %sRuntimeClassName = %q\n\n", s.GoName, s.NativeName, s.GoName, s.GoName, s.Type.NativeName)
		}
	}
	return goFile(header, pkg, "", imports, body.String())
}

func renderNamedType(b *strings.Builder, s model.Symbol) {
	goType := s.Type.GoType
	if goType == "" {
		goType = s.Type.Underlying
	}
	if goType == "" {
		goType = "uintptr"
	}
	doc := fmt.Sprintf("// %s is the raw projection of native %s.", s.GoName, s.NativeName)
	fmt.Fprintln(b, doc)
	if s.Type.Distinct || s.Kind == model.KindHandle || s.Kind == model.KindFixedArray {
		fmt.Fprintf(b, "type %s %s\n\n", s.GoName, goType)
	} else {
		fmt.Fprintf(b, "type %s = %s\n\n", s.GoName, goType)
	}
	if s.Kind == model.KindHandle {
		fmt.Fprintf(b, "const (\n\t// Null%s is the null handle.\n\tNull%s %s = 0\n", s.GoName, s.GoName, s.GoName)
		if s.Type.InvalidValue != "" {
			fmt.Fprintf(b, "\t// Invalid%s is distinct from the null handle.\n\tInvalid%s %s = %s(%s)\n", s.GoName, s.GoName, s.GoName, s.GoName, s.Type.InvalidValue)
		}
		b.WriteString(")\n\n")
	}
}

func renderStruct(b *strings.Builder, s model.Symbol) {
	fmt.Fprintf(b, "// %s preserves the native %s field order.\ntype %s struct {\n", s.GoName, s.NativeName, s.GoName)
	for _, f := range s.Type.Fields {
		name := f.Name
		if name == "" {
			name = "_"
		}
		typ := f.Type.GoType
		if typ == "" {
			typ = "uintptr"
		}
		fmt.Fprintf(b, "\t%s %s\n", name, typ)
	}
	b.WriteString("}\n\n")
}
func hasBitFields(t model.Type) bool {
	for _, f := range t.Fields {
		if f.BitField != nil {
			return true
		}
	}
	return false
}
func renderBitField(b *strings.Builder, s model.Symbol) {
	storage := "uint32"
	for _, f := range s.Type.Fields {
		if f.BitField != nil && f.BitField.StorageType != "" {
			storage = f.BitField.StorageType
			break
		}
	}
	fmt.Fprintf(b, "// %s stores native bit fields in their proven base storage.\ntype %s struct { bits %s }\n\n", s.GoName, s.GoName, storage)
	fmt.Fprintf(b, "// RawStorage returns the complete bit-field storage word.\nfunc (v %s) RawStorage() %s { return v.bits }\n\n", s.GoName, storage)
	for _, f := range s.Type.Fields {
		bf := f.BitField
		if bf == nil || bf.BitWidth == 0 {
			continue
		}
		mask := (uint64(1) << bf.BitWidth) - 1
		if bf.Signed {
			fmt.Fprintf(b, "// %s reads %s with C-compatible sign extension.\nfunc (v %s) %s() int32 {\n\traw := int32((uint64(v.bits) >> %d) & 0x%x)\n\tshift := uint32(32 - %d)\n\treturn raw << shift >> shift\n}\n\n", f.Name, f.NativeName, s.GoName, f.Name, bf.BitOffset, mask, bf.BitWidth)
			fmt.Fprintf(b, "// Set%s writes only the %d-bit field.\nfunc (v *%s) Set%s(value int32) {\n\tconst mask %s = 0x%x << %d\n\tv.bits = (v.bits &^ mask) | (%s(uint32(value)) << %d & mask)\n}\n\n", f.Name, bf.BitWidth, s.GoName, f.Name, storage, mask, bf.BitOffset, storage, bf.BitOffset)
		} else {
			fmt.Fprintf(b, "// %s reads the %d-bit field.\nfunc (v %s) %s() %s { return %s((uint64(v.bits) >> %d) & 0x%x) }\n\n", f.Name, bf.BitWidth, s.GoName, f.Name, f.Type.GoType, f.Type.GoType, bf.BitOffset, mask)
			fmt.Fprintf(b, "// Set%s writes only the %d-bit field.\nfunc (v *%s) Set%s(value %s) {\n\tconst mask %s = 0x%x << %d\n\tv.bits = (v.bits &^ mask) | (%s(value) << %d & mask)\n}\n\n", f.Name, bf.BitWidth, s.GoName, f.Name, f.Type.GoType, storage, mask, bf.BitOffset, storage, bf.BitOffset)
		}
	}
}

func renderUnion(b *strings.Builder, s model.Symbol, architecture string) {
	size, align := uint64(1), uint64(1)
	layoutIndex := 0
	for i, layout := range s.Type.Layouts {
		if architecture != "" && layout.Architecture == architecture {
			layoutIndex = i
			break
		}
	}
	if len(s.Type.Layouts) > layoutIndex {
		size = s.Type.Layouts[layoutIndex].Size
		align = s.Type.Layouts[layoutIndex].Alignment
	}
	if architecture == "386" && align > 4 {
		fmt.Fprintf(b, "// %s is %d-byte storage only. Native alignment is %d, which Go/386 cannot\n// express. Do not embed or pass this value by ABI; use an aligned buffer or bridge.\ntype %s struct { storage [%d]byte }\n\n", s.GoName, size, align, s.GoName, size)
	} else {
		anchor := alignmentType(align)
		fmt.Fprintf(b, "// %s is %d-byte union storage with %d-byte alignment. Accessors expose only proven views.\ntype %s struct {\n\t_ [0]%s\n\tstorage [%d]byte\n}\n\n", s.GoName, size, align, s.GoName, anchor, size)
	}
	for _, f := range s.Type.Fields {
		off, ok := unionOffset(*s.Type, f.Name, architecture)
		if !ok {
			continue
		}
		typ := f.Type.GoType
		if typ == "" {
			continue
		}
		fmt.Fprintf(b, "// %s reads the %s union view. The caller must track which member is active.\nfunc (v *%s) %s() %s { return *(*%s)(unsafe.Pointer(&v.storage[%d])) }\n\n", f.Name, f.NativeName, s.GoName, f.Name, typ, typ, off)
		fmt.Fprintf(b, "// Set%s writes the %s union view.\nfunc (v *%s) Set%s(value %s) { *(*%s)(unsafe.Pointer(&v.storage[%d])) = value }\n\n", f.Name, f.NativeName, s.GoName, f.Name, typ, typ, off)
	}
}
func unionOffset(t model.Type, name, architecture string) (uint64, bool) {
	if len(t.Layouts) == 0 {
		return 0, name == t.Fields[0].Name
	}
	layout := t.Layouts[0]
	for _, candidate := range t.Layouts {
		if architecture != "" && candidate.Architecture == architecture {
			layout = candidate
			break
		}
	}
	for _, f := range layout.Fields {
		if f.Name == name {
			return f.Offset, true
		}
	}
	return 0, false
}
func alignmentType(n uint64) string {
	switch n {
	case 8:
		return "uint64"
	case 4:
		return "uint32"
	case 2:
		return "uint16"
	default:
		return "byte"
	}
}

func renderFlexible(b *strings.Builder, s model.Symbol) {
	fmt.Fprintf(b, "// %s is only the fixed header of a native flexible-array record.\n// The trailing array is intentionally not represented as [1]T.\ntype %s struct {\n", s.GoName, s.GoName)
	for _, f := range s.Type.Fields {
		fmt.Fprintf(b, "\t%s %s\n", f.Name, f.Type.GoType)
	}
	b.WriteString("}\n\n")
	elem := "byte"
	if s.Type.FlexibleElement != nil && s.Type.FlexibleElement.GoType != "" {
		elem = s.Type.FlexibleElement.GoType
	}
	fmt.Fprintf(b, "// DataView returns a bounded view over caller-owned trailing storage. The view\n// cannot outlive base and must not be retained by Windows after the call.\nfunc (h *%s) DataView(base unsafe.Pointer, allocatedBytes uintptr) ([]%s, error) {\n\theader := unsafe.Sizeof(*h)\n\tif base == nil || allocatedBytes < header { return nil, fmt.Errorf(\"%s: buffer smaller than header\") }\n\tcount := uintptr(h.Size)\n\tif count > allocatedBytes-header || count > uintptr(^uint(0)>>1) { return nil, fmt.Errorf(\"%s: trailing length outside allocation\") }\n\tstart := unsafe.Add(base, header)\n\treturn unsafe.Slice((*%s)(start), int(count)), nil\n}\n\n", s.GoName, elem, s.GoName, s.GoName, elem)
}

func renderArchTypes(pkg string, symbols []model.Symbol, header, arch string) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{}
	for _, s := range symbols {
		if s.Architecture == "neutral" && s.Type != nil && s.Kind == model.KindUnion && len(s.Type.Layouts) > 1 {
			imports["unsafe"] = true
			renderUnion(&body, s, arch)
			continue
		}
		if s.Architecture != arch || s.Type == nil {
			continue
		}
		if s.Kind == model.KindStruct {
			renderStruct(&body, s)
		} else {
			renderNamedType(&body, s)
		}
	}
	if body.Len() == 0 {
		return nil, nil
	}
	return goFile(header, pkg, "windows && "+arch, imports, body.String())
}

func renderConstants(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
	var body strings.Builder
	for _, s := range symbols {
		if s.Kind != model.KindConstant || s.Constant == nil || s.Architecture != "neutral" {
			continue
		}
		fmt.Fprintf(&body, "// %s is native constant %s.\nconst %s %s = %s\n\n", s.GoName, s.NativeName, s.GoName, s.Constant.Type.GoType, s.Constant.Value)
	}
	return goFile(header, pkg, "", nil, body.String())
}

func renderCallbacks(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
	var body strings.Builder
	for _, s := range symbols {
		if s.Kind != model.KindCallback || s.Type == nil {
			continue
		}
		fmt.Fprintf(&body, "// %s is a raw callback address. Its owner must keep the callback alive and\n// prevent invocation after release.\ntype %s %s\n\n", s.GoName, s.GoName, s.Type.GoType)
	}
	return goFile(header, pkg, "", nil, body.String())
}

func renderCOM(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
	var body strings.Builder
	for _, s := range symbols {
		if s.Kind != model.KindCOMInterface || s.Type == nil {
			continue
		}
		fmt.Fprintf(&body, "// %s is the raw COM interface pointer. Release remains explicit.\ntype %s struct { VTable *%sVTable }\n\n", s.GoName, s.GoName, s.GoName)
		fmt.Fprintf(&body, "// %sVTable preserves metadata method order.\ntype %sVTable struct {\n", s.GoName, s.GoName)
		methods := append([]model.Method(nil), s.Type.Methods...)
		sort.Slice(methods, func(i, j int) bool { return methods[i].VTableIndex < methods[j].VTableIndex })
		for _, m := range methods {
			fmt.Fprintf(&body, "\t%s uintptr // slot %d\n", m.Name, m.VTableIndex)
		}
		body.WriteString("}\n\n")
		if s.GUID != nil {
			fmt.Fprintf(&body, "// IID%s is the interface identifier.\nvar IID%s = GUID{Data1: 0x%08x, Data2: 0x%04x, Data3: 0x%04x, Data4: [8]uint8{%s}}\n\n", s.GoName, s.GoName, s.GUID.Data1, s.GUID.Data2, s.GUID.Data3, byteList(s.GUID.Data4))
		}
	}
	return goFile(header, pkg, "", nil, body.String())
}
func byteList(v [8]uint8) string {
	parts := make([]string, 8)
	for i, b := range v {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	return strings.Join(parts, ",")
}

func renderFunctions(pkg string, symbols []model.Symbol, header, modulePath string) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{}
	var funcs []model.Symbol
	for _, s := range symbols {
		if s.Kind == model.KindFunction && s.Status == model.StatusGeneratedPureGo && s.Function != nil {
			funcs = append(funcs, s)
		}
	}
	if len(funcs) > 0 {
		imports[strings.TrimSuffix(modulePath, "/")+"/runtime/winabi"] = true
	}
	for _, s := range funcs {
		fn := s.Function
		fmt.Fprintf(&body, "var proc%s = winabi.NewSystemProc(%q, %q)\n\n", s.GoName, fn.DLL, fn.EntryPoint)
		ptrs := false
		params := make([]string, len(fn.Parameters))
		args := make([]string, len(fn.Parameters))
		for i, p := range fn.Parameters {
			typ := p.Type.GoType
			if typ == "" {
				typ = "uintptr"
			}
			params[i] = p.Name + " " + typ
			args[i], ptrs = callArg(p.Name, p.Type, ptrs)
		}
		ret := fn.Return.GoType
		returns := ""
		if ret != "" {
			returns = ret
		}
		if fn.SetLastError {
			if returns != "" {
				returns = "(" + returns + ", winabi.LastError)"
			} else {
				returns = "winabi.LastError"
			}
		}
		fmt.Fprintf(&body, "// %s calls native %s!%s. The raw layer does not infer failure from a\n// nonzero last-error value; apply the documented rule %q first.\nfunc %s(%s) %s {\n", s.GoName, fn.DLL, fn.EntryPoint, fn.FailureRule, s.GoName, strings.Join(params, ", "), returns)
		if ptrs {
			imports["runtime"] = true
			imports["unsafe"] = true
		}
		fmt.Fprintf(&body, "\tr1, _, lastErr := proc%s.Call(%s)\n", s.GoName, strings.Join(args, ", "))
		for _, p := range fn.Parameters {
			if isPointerType(p.Type) {
				fmt.Fprintf(&body, "\truntime.KeepAlive(%s)\n", p.Name)
			}
		}
		switch {
		case ret == "" && fn.SetLastError:
			body.WriteString("\t_ = r1\n\treturn lastErr\n")
		case ret == "":
			body.WriteString("\t_ = r1\n\t_ = lastErr\n")
		case fn.SetLastError:
			fmt.Fprintf(&body, "\treturn %s, lastErr\n", returnExpression(fn.Return, &imports))
		default:
			fmt.Fprintf(&body, "\t_ = lastErr\n\treturn %s\n", returnExpression(fn.Return, &imports))
		}
		body.WriteString("}\n\n")
	}
	return goFile(header, pkg, "windows", imports, body.String())
}

func returnExpression(t model.Type, imports *map[string]bool) string {
	if isPointerType(t) {
		if t.GoType == "unsafe.Pointer" {
			return "winabi.UnsafePointerFromUintptr(r1)"
		}
		return "(" + t.GoType + ")(winabi.UnsafePointerFromUintptr(r1))"
	}
	return t.GoType + "(r1)"
}
func callArg(name string, t model.Type, hadPtr bool) (string, bool) {
	if isPointerType(t) {
		return "uintptr(unsafe.Pointer(" + name + "))", true
	}
	return "uintptr(" + name + ")", hadPtr
}
func isPointerType(t model.Type) bool {
	return t.PointerDepth > 0 || strings.HasPrefix(t.GoType, "*") || t.GoType == "unsafe.Pointer"
}

func renderAvailability(pkg string, symbols []model.Symbol, header string) ([]byte, error) {
	var body strings.Builder
	imports := map[string]bool{}
	for _, s := range symbols {
		if s.Kind != model.KindFunction || s.Function == nil || !s.Function.OptionalExport || s.Status != model.StatusGeneratedPureGo {
			continue
		}
		fmt.Fprintf(&body, "// Is%sAvailable reports whether the optional export resolves safely.\nfunc Is%sAvailable() bool { return proc%s.Available() }\n\n", s.GoName, s.GoName, s.GoName)
	}
	return goFile(header, pkg, "windows", imports, body.String())
}

func renderBridge(inv model.Inventory) (map[string][]byte, error) {
	out := map[string][]byte{}
	var bridges []model.Symbol
	for _, s := range inv.Symbols {
		if s.Status == model.StatusGeneratedCGOBridge && s.Function != nil && s.SourceType == "project-fixture" {
			bridges = append(bridges, s)
		}
	}
	if len(bridges) == 0 {
		return out, nil
	}
	sort.Slice(bridges, func(i, j int) bool { return bridges[i].ID < bridges[j].ID })
	header := generatedHeader(inv, bridges)
	var body strings.Builder
	body.WriteString("/*\n#include <stdint.h>\ntypedef struct { uint32_t LowDateTime; uint32_t HighDateTime; } winabi_FILETIME;\nstatic uint64_t winabi_fixture_filetime_value(winabi_FILETIME value) { return ((uint64_t)value.HighDateTime << 32) | value.LowDateTime; }\n*/\nimport \"C\"\n\n// FixtureStructByValue proves that aggregate classification occurs in C.\nfunc FixtureStructByValue(lowDateTime, highDateTime uint32) uint64 {\n\tv := C.winabi_FILETIME{LowDateTime: C.uint32_t(lowDateTime), HighDateTime: C.uint32_t(highDateTime)}\n\treturn uint64(C.winabi_fixture_filetime_value(v))\n}\n")
	b, err := goFile(header, "generated", "windows && cgo", nil, body.String())
	if err != nil {
		return nil, err
	}
	out["bridge/generated/zbridge_windows_cgo.go"] = b
	stub, err := goFile(header, "generated", "!windows || !cgo", nil, "// CGO-disabled builds intentionally expose no bridge-only API.\n")
	if err != nil {
		return nil, err
	}
	out["bridge/generated/zbridge_nocgo.go"] = stub
	return out, nil
}

func goFile(header, pkg, build string, imports map[string]bool, body string) ([]byte, error) {
	var b bytes.Buffer
	if build != "" {
		fmt.Fprintf(&b, "//go:build %s\n\n", build)
	}
	b.WriteString(header)
	fmt.Fprintf(&b, "\npackage %s\n", pkg)
	if len(imports) > 0 {
		keys := make([]string, 0, len(imports))
		for k := range imports {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\nimport (\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "\t%q\n", k)
		}
		b.WriteString(")\n")
	}
	if body != "" {
		b.WriteByte('\n')
		b.WriteString(body)
	}
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt generated source: %w\n%s", err, b.String())
	}
	return formatted, nil
}

func packageDir(ns string) string {
	if ns == "" {
		return "global"
	}
	return strings.ToLower(strings.ReplaceAll(ns, ".", "_"))
}
func packageName(ns string) string {
	s := packageDir(ns)
	if i := strings.LastIndexByte(s, '_'); i >= 0 {
		s = s[i+1:]
	}
	if s == "" {
		s = "global"
	}
	return s
}

func Write(root string, t Tree) error {
	groups := map[string]map[string][]byte{}
	for path, data := range t.Files {
		top := strings.Split(filepath.ToSlash(path), "/")[0]
		if top != "bindings" && top != "bridge" {
			return fmt.Errorf("emitter path outside owned roots: %s", path)
		}
		rel := strings.TrimPrefix(filepath.ToSlash(path), top+"/")
		if groups[top] == nil {
			groups[top] = map[string][]byte{}
		}
		groups[top][rel] = data
	}
	for _, top := range []string{"bindings", "bridge"} {
		files := groups[top]
		if len(files) == 0 {
			continue
		}
		sub := "generated"
		filtered := map[string][]byte{}
		for rel, b := range files {
			if !strings.HasPrefix(rel, sub+"/") {
				return fmt.Errorf("unexpected %s path %s", top, rel)
			}
			filtered[strings.TrimPrefix(rel, sub+"/")] = b
		}
		if err := writeAtomic(filepath.Join(root, top, sub), filtered, t.ManifestHash); err != nil {
			return err
		}
	}
	return nil
}

func writeAtomic(dest string, files map[string][]byte, hash string) error {
	parent := filepath.Dir(dest)
	if err := os.MkdirAll(parent, 0o755); err != nil {
		return err
	}
	stage, err := os.MkdirTemp(parent, ".winapigen-")
	if err != nil {
		return err
	}
	defer os.RemoveAll(stage)
	for rel, data := range files {
		path := filepath.Join(stage, filepath.FromSlash(rel))
		if err = safeGeneratedPath(stage, path); err != nil {
			return err
		}
		if err = os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err = os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
	}
	manifest, _ := json.MarshalIndent(map[string]any{"schemaVersion": 1, "manifestHash": hash, "files": sortedFileNames(files)}, "", "  ")
	manifest = append(manifest, '\n')
	if err = os.WriteFile(filepath.Join(stage, ".winapigen.json"), manifest, 0o644); err != nil {
		return err
	}
	if _, err = os.Stat(dest); err == nil {
		if _, markErr := os.Stat(filepath.Join(dest, ".winapigen.json")); markErr != nil {
			return fmt.Errorf("refusing to replace unowned directory %s", dest)
		}
		backup := dest + ".old"
		if _, e := os.Stat(backup); e == nil {
			return fmt.Errorf("stale generated backup %s", backup)
		}
		if err = os.Rename(dest, backup); err != nil {
			return err
		}
		if err = os.Rename(stage, dest); err != nil {
			_ = os.Rename(backup, dest)
			return err
		}
		return os.RemoveAll(backup)
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.Rename(stage, dest)
}
func safeGeneratedPath(root, path string) error {
	rel, err := filepath.Rel(root, path)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("generated path escapes staging root")
	}
	return nil
}
func sortedFileNames(m map[string][]byte) []string {
	v := make([]string, 0, len(m))
	for k := range m {
		v = append(v, filepath.ToSlash(k))
	}
	sort.Strings(v)
	return v
}
