package generator

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/zzuf/GoWin-AFO/generator/internal/emit"
	"github.com/zzuf/GoWin-AFO/generator/internal/slice"
)

func TestGenerateRecreatesReviewedSliceWithRootModule(t *testing.T) {
	root := tempGenerationRoot(t)
	for i := 0; i < 2; i++ {
		if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err != nil {
			t.Fatal(err)
		}
	}
	path := filepath.Join(root, "bindings", "win32", "kernel32", "zfunctions_kernel_windows.go")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(data, []byte(`"example.com/renamed/runtime/winabi"`)) {
		t.Fatal("root module path was not propagated to reviewed slice")
	}
	if err := os.Remove(path); err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err != nil {
		t.Fatal(err)
	}
	restored, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(restored, data) {
		t.Fatal("deleted slice output was not reconstructed deterministically")
	}
}

func TestGenerateSliceFailurePreservesRawTreeAndReports(t *testing.T) {
	root := tempGenerationRoot(t)
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err != nil {
		t.Fatal(err)
	}
	raw := filepath.Join(root, "bindings", "generated", "windows_win32_foundation", "ztypes_generated.go")
	report := filepath.Join(root, "coverage", "latest.json")
	previousRaw := []byte("// Code generated by winapigen 0.1.0; DO NOT EDIT.\n// previous raw tree\npackage foundation\n")
	if err := os.WriteFile(raw, previousRaw, 0o644); err != nil {
		t.Fatal(err)
	}
	previousReport, err := os.ReadFile(report)
	if err != nil {
		t.Fatal(err)
	}
	blocked := filepath.Join(root, "bindings", "win32", "foundation", "ztypes_base.go")
	if err := os.Remove(blocked); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(blocked, 0o755); err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err == nil {
		t.Fatal("expected blocked slice destination")
	}
	if got, err := os.ReadFile(raw); err != nil || !bytes.Equal(got, previousRaw) {
		t.Fatalf("raw tree changed after failed generation: %q, %v", got, err)
	}
	if got, err := os.ReadFile(report); err != nil || !bytes.Equal(got, previousReport) {
		t.Fatalf("report changed after failed generation: %q, %v", got, err)
	}
}

func TestGenerateRejectsUnknownFileInsideRawTree(t *testing.T) {
	root := tempGenerationRoot(t)
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err != nil {
		t.Fatal(err)
	}
	unknown := filepath.Join(root, "bindings", "generated", "windows_win32_foundation", "handwritten.go")
	if err := os.WriteFile(unknown, []byte("package foundation\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err == nil {
		t.Fatal("expected unknown-file collision")
	}
	if got, err := os.ReadFile(unknown); err != nil || string(got) != "package foundation\n" {
		t.Fatalf("unknown file was removed: %q, %v", got, err)
	}
}

func TestGenerateRejectsHandwrittenCoverageReport(t *testing.T) {
	root := tempGenerationRoot(t)
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(root, "coverage", "latest.json")
	if err := os.WriteFile(path, []byte("user notes"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true}); err == nil {
		t.Fatal("expected report collision")
	}
	if got, err := os.ReadFile(path); err != nil || string(got) != "user notes" {
		t.Fatalf("handwritten report was overwritten: %q, %v", got, err)
	}
}

func TestStagedRawDumpIsNotWrittenOnSliceFailure(t *testing.T) {
	root := tempGenerationRoot(t)
	result, err := Generate(context.Background(), GenerateOptions{Root: root, Write: true})
	if err != nil {
		t.Fatal(err)
	}
	raw, err := emit.Render(result.Inventory, "example.com/renamed")
	if err != nil {
		t.Fatal(err)
	}
	reviewed, err := slice.Render(root, "example.com/renamed", Version)
	if err != nil {
		t.Fatal(err)
	}
	dump := filepath.Join(root, "coverage", "raw", "fixture.json")
	if err := os.MkdirAll(filepath.Dir(dump), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(dump, []byte("{\"prior\":true}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := writeGeneration(root, result.Inventory, result.Coverage, raw, reviewed, map[string][]byte{"coverage/raw/fixture.json": []byte("{\"next\":true}\n")}); err != nil {
		t.Fatal(err)
	}
	if got, err := os.ReadFile(dump); err != nil || string(got) != "{\"next\":true}\n" {
		t.Fatalf("raw dump was not committed with generation: %q, %v", got, err)
	}
	blocked := filepath.Join(root, "bindings", "win32", "foundation", "ztypes_base.go")
	if err := os.Remove(blocked); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(blocked, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := writeGeneration(root, result.Inventory, result.Coverage, raw, reviewed, map[string][]byte{"coverage/raw/fixture.json": []byte("{\"after\":true}\n")}); err == nil {
		t.Fatal("expected blocked slice destination")
	}
	if got, err := os.ReadFile(dump); err != nil || string(got) != "{\"next\":true}\n" {
		t.Fatalf("raw dump changed after failure: %q, %v", got, err)
	}
}

func TestGenerationRollbackRetainsBackupWhenRestoreFails(t *testing.T) {
	for _, failRestore := range []bool{false, true} {
		name := "restores"
		if failRestore {
			name = "retains-backup"
		}
		t.Run(name, func(t *testing.T) {
			root := t.TempDir()
			stage := filepath.Join(root, "stage")
			for _, name := range []string{"a", "b"} {
				for _, base := range []string{root, stage} {
					path := filepath.Join(base, "coverage", name)
					if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
						t.Fatal(err)
					}
					if err := os.WriteFile(path, []byte(base), 0o644); err != nil {
						t.Fatal(err)
					}
				}
			}
			installFailure := errors.New("injected install failure")
			restoreFailure := errors.New("injected restore failure")
			ops := transactionOps{rename: func(from, to string) error {
				if from == filepath.Join(stage, "coverage", "b") && to == filepath.Join(root, "coverage", "b") {
					return installFailure
				}
				if failRestore && from == filepath.Join(stage, "backups", "0000") {
					return restoreFailure
				}
				return os.Rename(from, to)
			}, remove: os.Remove, removeAll: os.RemoveAll}
			err := commitGenerationWithOps(root, stage, []generatedTarget{{path: "coverage/a"}, {path: "coverage/b"}}, ops)
			if !errors.Is(err, installFailure) {
				t.Fatalf("missing install error: %v", err)
			}
			if got, err := os.ReadFile(filepath.Join(root, "coverage", "b")); err != nil || string(got) != root {
				t.Fatalf("second target was not restored: %q, %v", got, err)
			}
			if failRestore {
				var retained *retainedStageError
				if !errors.Is(err, restoreFailure) || !errors.As(err, &retained) || !strings.Contains(err.Error(), stage) {
					t.Fatalf("restore failure and backup path not reported: %v", err)
				}
				if got, err := os.ReadFile(filepath.Join(stage, "backups", "0000")); err != nil || string(got) != root {
					t.Fatalf("backup not retained: %q, %v", got, err)
				}
			} else if got, err := os.ReadFile(filepath.Join(root, "coverage", "a")); err != nil || string(got) != root {
				t.Fatalf("first target was not restored: %q, %v", got, err)
			}
		})
	}
}

func tempGenerationRoot(t *testing.T) string {
	t.Helper()
	project, err := filepath.Abs("..")
	if err != nil {
		t.Fatal(err)
	}
	root := t.TempDir()
	for _, path := range []string{"sources.lock.json", "generator/testdata/e2e/source.json"} {
		data, err := os.ReadFile(filepath.Join(project, filepath.FromSlash(path)))
		if err != nil {
			t.Fatal(err)
		}
		dest := filepath.Join(root, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(dest, data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.com/renamed\n\ngo 1.24.0\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}
