// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 8ad8a6155747f09499c3edd6850ccf30545f16ff5c36dee73c7620fb2ecb5534

package foundation

// ProjectionStatus is a machine-stable symbol projection status.
type ProjectionStatus string

const (
	GeneratedPureGo   ProjectionStatus = "generated-purego"
	GeneratedTypeOnly ProjectionStatus = "generated-type-only"
)

// SymbolProjection records the audited status of one generated symbol.
type SymbolProjection struct {
	ID     string
	Native string
	Status ProjectionStatus
	Reason string
}

// SliceProjectionInventory is deterministically sorted by symbol ID.
var SliceProjectionInventory = [...]SymbolProjection{
	{ID: "win32|Windows.Win32.Foundation|guid|GUID|any|guid(u32,u16,u16,[8]u8)|0|desktop", Native: "GUID", Status: GeneratedPureGo, Reason: "layout verified by fixed-width fields"},
	{ID: "win32|Windows.Win32.Foundation|handle|HANDLE|any|opaque(uintptr)|0|desktop", Native: "HANDLE", Status: GeneratedPureGo, Reason: "pointer-sized opaque value"},
	{ID: "win32|Windows.Win32.Foundation|union|LARGE_INTEGER|386|union(i64,u32+i32)|0|desktop", Native: "LARGE_INTEGER", Status: GeneratedTypeOnly, Reason: "native alignment 8 is not representable by Go/386; callable wrappers use aligned scratch storage"},
	{ID: "win32|Windows.Win32.Foundation|union|LARGE_INTEGER|amd64|union(i64,u32+i32)|0|desktop", Native: "LARGE_INTEGER", Status: GeneratedPureGo, Reason: "size 8 and alignment 8 with typed accessors"},
	{ID: "win32|Windows.Win32.Foundation|union|LARGE_INTEGER|arm64|union(i64,u32+i32)|0|desktop", Native: "LARGE_INTEGER", Status: GeneratedPureGo, Reason: "size 8 and alignment 8 with typed accessors"},
}
