//go:build amd64 || arm64

// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 8ad8a6155747f09499c3edd6850ccf30545f16ff5c36dee73c7620fb2ecb5534

package foundation

// LargeIntegerDirectABI is true where Go and the native ABI both align the
// 64-bit union storage to 8 bytes.
const LargeIntegerDirectABI = true

// LARGE_INTEGER projects the native union through one aligned 64-bit storage
// field. Accessors expose overlapping low/high views.
type LARGE_INTEGER struct {
	storage [1]int64
}

func (value *LARGE_INTEGER) Int64() int64 {
	if value == nil {
		return 0
	}
	return value.storage[0]
}

func (value *LARGE_INTEGER) SetInt64(number int64) {
	value.storage[0] = number
}

func (value *LARGE_INTEGER) LowPart() uint32 {
	if value == nil {
		return 0
	}
	return uint32(uint64(value.storage[0]))
}

func (value *LARGE_INTEGER) HighPart() int32 {
	if value == nil {
		return 0
	}
	return int32(uint64(value.storage[0]) >> 32)
}

func (value *LARGE_INTEGER) SetParts(low uint32, high int32) {
	value.storage[0] = int64(uint64(low) | uint64(uint32(high))<<32)
}

// ULARGE_INTEGER is the aligned unsigned native union storage.
type ULARGE_INTEGER struct {
	storage [1]uint64
}

func (value *ULARGE_INTEGER) Uint64() uint64 {
	if value == nil {
		return 0
	}
	return value.storage[0]
}

func (value *ULARGE_INTEGER) SetUint64(number uint64) {
	value.storage[0] = number
}

func (value *ULARGE_INTEGER) LowPart() uint32 {
	if value == nil {
		return 0
	}
	return uint32(value.storage[0])
}

func (value *ULARGE_INTEGER) HighPart() uint32 {
	if value == nil {
		return 0
	}
	return uint32(value.storage[0] >> 32)
}

func (value *ULARGE_INTEGER) SetParts(low, high uint32) {
	value.storage[0] = uint64(low) | uint64(high)<<32
}
