// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 8ad8a6155747f09499c3edd6850ccf30545f16ff5c36dee73c7620fb2ecb5534

package foundation

import (
	"unsafe"

	"github.com/zzuf/GoWin-AFO/runtime/winabi"
)

// CHAR is the native signed 8-bit character type.
type CHAR int8

// BYTE is the native unsigned 8-bit byte type.
type BYTE uint8

// SHORT is the native signed 16-bit integer type.
type SHORT int16

// USHORT is the native unsigned 16-bit integer type.
type USHORT uint16

// INT is the Windows ABI 32-bit C int type.
type INT int32

// UINT is the Windows ABI 32-bit unsigned C int type.
type UINT uint32

// LONG remains 32-bit under Windows LLP64.
type LONG int32

// ULONG remains 32-bit under Windows LLP64.
type ULONG uint32

// LONGLONG is a signed 64-bit integer.
type LONGLONG int64

// ULONGLONG is an unsigned 64-bit integer.
type ULONGLONG uint64

// WCHAR is one UTF-16 code unit.
type WCHAR uint16

// BOOL is the native signed 32-bit Boolean representation.
type BOOL int32

const (
	FALSE BOOL = 0
	TRUE  BOOL = 1
)

// BOOLEAN is the native unsigned 8-bit Boolean representation.
type BOOLEAN uint8

// HRESULT preserves the native signed 32-bit status.
type HRESULT = winabi.HRESULT

// NTSTATUS preserves the native signed 32-bit status.
type NTSTATUS = winabi.NTSTATUS

// SIZE_T is an unsigned pointer-sized size.
type SIZE_T uintptr

// SSIZE_T is a signed pointer-sized size.
type SSIZE_T winabi.SignedPointer

// INT_PTR is a signed pointer-sized integer.
type INT_PTR winabi.SignedPointer

// UINT_PTR is an unsigned pointer-sized integer.
type UINT_PTR uintptr

// LONG_PTR is a signed pointer-sized integer.
type LONG_PTR winabi.SignedPointer

// ULONG_PTR is an unsigned pointer-sized integer.
type ULONG_PTR uintptr

// HANDLE is a pointer-sized opaque native handle. Zero and
// INVALID_HANDLE_VALUE are distinct sentinels.
type HANDLE uintptr

// HMODULE is a distinct module handle type.
type HMODULE uintptr

// HWND is a distinct window handle type.
type HWND uintptr

// HKEY is a distinct registry key handle type.
type HKEY uintptr

const INVALID_HANDLE_VALUE HANDLE = ^HANDLE(0)

// PCWSTR is a borrowed pointer to NUL-terminated UTF-16 input.
type PCWSTR *uint16

// PWSTR is a borrowed pointer to writable NUL-terminated UTF-16 data.
type PWSTR *uint16

// PCSTR is a borrowed pointer to NUL-terminated narrow input.
type PCSTR *byte

// PSTR is a borrowed pointer to writable NUL-terminated narrow data.
type PSTR *byte

// GUID uses the verified native 16-byte GUID layout.
type GUID = winabi.GUID

// FILETIME is a 64-bit count represented as two native DWORD fields.
type FILETIME struct {
	LowDateTime  uint32
	HighDateTime uint32
}

// SYSTEMTIME is the native calendar-time structure.
type SYSTEMTIME struct {
	Year         uint16
	Month        uint16
	DayOfWeek    uint16
	Day          uint16
	Hour         uint16
	Minute       uint16
	Second       uint16
	Milliseconds uint16
}

// SECURITY_ATTRIBUTES has pointer-width-dependent padding determined by Go's
// windows/386, windows/amd64, and windows/arm64 layouts.
type SECURITY_ATTRIBUTES struct {
	Length             uint32
	SecurityDescriptor unsafe.Pointer
	InheritHandle      BOOL
}
