// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 8ad8a6155747f09499c3edd6850ccf30545f16ff5c36dee73c7620fb2ecb5534

package foundation

import "encoding/binary"

// LargeIntegerDirectABI is false on 386 because MSVC gives LARGE_INTEGER
// 8-byte alignment while Go/386 cannot express alignment greater than 4.
const LargeIntegerDirectABI = false

// LARGE_INTEGER is size-correct storage on 386 but is not safe to embed as a
// direct C union. Call wrappers that need it use an 8-byte-aligned scratch view.
type LARGE_INTEGER struct {
	storage [2]uint32
}

// Int64 reads the complete signed union value.
func (value *LARGE_INTEGER) Int64() int64 {
	if value == nil {
		return 0
	}
	return int64(uint64(value.storage[0]) | uint64(value.storage[1])<<32)
}

// SetInt64 writes the complete signed union value.
func (value *LARGE_INTEGER) SetInt64(number int64) {
	value.storage[0] = uint32(number)
	value.storage[1] = uint32(uint64(number) >> 32)
}

func (value *LARGE_INTEGER) LowPart() uint32 {
	if value == nil {
		return 0
	}
	return value.storage[0]
}

func (value *LARGE_INTEGER) HighPart() int32 {
	if value == nil {
		return 0
	}
	return int32(value.storage[1])
}

func (value *LARGE_INTEGER) SetParts(low uint32, high int32) {
	value.storage = [2]uint32{low, uint32(high)}
}

// ULARGE_INTEGER has the same 386 alignment limitation as LARGE_INTEGER.
type ULARGE_INTEGER struct {
	storage [8]byte
}

func (value *ULARGE_INTEGER) Uint64() uint64 {
	if value == nil {
		return 0
	}
	return binary.LittleEndian.Uint64(value.storage[:])
}

func (value *ULARGE_INTEGER) SetUint64(number uint64) {
	binary.LittleEndian.PutUint64(value.storage[:], number)
}

func (value *ULARGE_INTEGER) LowPart() uint32 {
	if value == nil {
		return 0
	}
	return binary.LittleEndian.Uint32(value.storage[0:4])
}

func (value *ULARGE_INTEGER) HighPart() uint32 {
	if value == nil {
		return 0
	}
	return binary.LittleEndian.Uint32(value.storage[4:8])
}

func (value *ULARGE_INTEGER) SetParts(low, high uint32) {
	binary.LittleEndian.PutUint32(value.storage[0:4], low)
	binary.LittleEndian.PutUint32(value.storage[4:8], high)
}
