// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.CPP UnionMetadata WinMD
// Source-Version: 10.0.26100.7705
// Manifest-SHA256: 24c85fd320cf36e0b22677ac3aa6b0bf907e184edcd551b9a232efe365bb168e

package foundation

import (
	"github.com/zzuf/GoWin-AFO/runtime/winabi"
	"github.com/zzuf/GoWin-AFO/runtime/winrt"
)

// RuntimeClassURI is the metadata name for Windows.Foundation.Uri.
const RuntimeClassURI = "Windows.Foundation.Uri"

// GetURIActivationFactory obtains an explicitly owned IActivationFactory.
// The caller must call Release on a successful result.
func GetURIActivationFactory() (*winrt.IActivationFactory, winabi.HRESULT) {
	return winrt.GetActivationFactory(RuntimeClassURI)
}

// URIProjection records the end-to-end slice classification.
var URIProjection = struct {
	NativeName string
	Status     string
	Backend    string
	Reason     string
}{
	NativeName: RuntimeClassURI,
	Status:     "generated-purego",
	Backend:    "purego-syscall",
	Reason:     "HSTRING plus RoGetActivationFactory integer/pointer ABI",
}
