package oracle

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
)

// Generate returns deterministic C++ source. The source uses compile-time type
// assertions for function pointers and emits layout facts as JSON when run.
func Generate(input Manifest) ([]byte, error) {
	if err := input.Validate(); err != nil {
		return nil, err
	}
	m := sortedManifest(input)
	canonical, err := json.Marshal(m)
	if err != nil {
		return nil, fmt.Errorf("canonicalize manifest: %w", err)
	}
	sum := sha256.Sum256(canonical)
	manifestHash := hex.EncodeToString(sum[:])

	var b bytes.Buffer
	b.WriteString("// Code generated by GoWin-AFO ABI oracle. DO NOT EDIT.\n")
	b.WriteString("// Generator: abi-oracle " + GeneratorVersion + "; source: " + m.SourceID + "; SDK: " + m.SDKVersion + "; manifest SHA-256: " + manifestHash + "\n\n")

	defineNames := make([]string, 0, len(m.Defines))
	for name := range m.Defines {
		defineNames = append(defineNames, name)
	}
	sort.Strings(defineNames)
	for _, name := range defineNames {
		fmt.Fprintf(&b, "#ifndef %s\n#define %s %s\n#endif\n", name, name, m.Defines[name])
	}
	b.WriteString("#ifndef CINTERFACE\n#define CINTERFACE\n#endif\n")
	b.WriteString("#ifndef COBJMACROS\n#define COBJMACROS\n#endif\n\n")
	for _, include := range m.Includes {
		fmt.Fprintf(&b, "#include <%s>\n", include)
	}
	b.WriteString(`#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <type_traits>

#define ABI_STRINGIFY_INNER(value) #value
#define ABI_STRINGIFY(value) ABI_STRINGIFY_INNER(value)

#if defined(__clang__)
static constexpr const char* abi_compiler_family = "clang-cl";
static constexpr const char* abi_compiler_version = ABI_STRINGIFY(__clang_major__) "." ABI_STRINGIFY(__clang_minor__) "." ABI_STRINGIFY(__clang_patchlevel__);
#elif defined(_MSC_VER)
static constexpr const char* abi_compiler_family = "msvc";
static constexpr const char* abi_compiler_version = ABI_STRINGIFY(_MSC_FULL_VER);
#else
#error Unsupported compiler: use MSVC or clang-cl.
#endif

#if defined(_M_ARM64EC)
static constexpr const char* abi_compiled_architecture = "arm64ec";
#elif defined(_M_IX86)
static constexpr const char* abi_compiled_architecture = "386";
#elif defined(_M_X64)
static constexpr const char* abi_compiled_architecture = "amd64";
#elif defined(_M_ARM64)
static constexpr const char* abi_compiled_architecture = "arm64";
#else
#error Unsupported Windows architecture.
#endif

static void abi_json_string(const char* value) {
  std::putchar('"');
  for (const unsigned char* p = reinterpret_cast<const unsigned char*>(value); *p; ++p) {
    switch (*p) {
      case '"': std::fputs("\\\"", stdout); break;
      case '\\': std::fputs("\\\\", stdout); break;
      case '\b': std::fputs("\\b", stdout); break;
      case '\f': std::fputs("\\f", stdout); break;
      case '\n': std::fputs("\\n", stdout); break;
      case '\r': std::fputs("\\r", stdout); break;
      case '\t': std::fputs("\\t", stdout); break;
      default:
        if (*p < 0x20) std::printf("\\u%04x", static_cast<unsigned>(*p));
        else std::putchar(*p);
    }
  }
  std::putchar('"');
}

static void abi_print_guid(const GUID& value) {
  std::printf("%08lx-%04hx-%04hx-%02hhx%02hhx-%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx",
      static_cast<unsigned long>(value.Data1), value.Data2, value.Data3,
      value.Data4[0], value.Data4[1], value.Data4[2], value.Data4[3],
      value.Data4[4], value.Data4[5], value.Data4[6], value.Data4[7]);
}

static unsigned long long abi_first_set_bit(const unsigned char* bytes, std::size_t size) {
  for (std::size_t byte = 0; byte < size; ++byte) {
    for (unsigned bit = 0; bit < 8; ++bit) {
      if ((bytes[byte] & (1u << bit)) != 0) return static_cast<unsigned long long>(byte * 8 + bit);
    }
  }
  return static_cast<unsigned long long>(size * 8);
}

static unsigned long long abi_popcount(const unsigned char* bytes, std::size_t size) {
  unsigned long long count = 0;
  for (std::size_t byte = 0; byte < size; ++byte) {
    unsigned value = bytes[byte];
    while (value != 0) { count += value & 1u; value >>= 1; }
  }
  return count;
}

`)

	for i, p := range m.Functions {
		fmt.Fprintf(&b, "using abi_expected_function_%d = %s;\n", i, p.ExpectedType)
		fmt.Fprintf(&b, "static_assert(std::is_same_v<decltype(%s), abi_expected_function_%d>, \"ABI function pointer mismatch: %s\");\n", p.Expression, i, cppQuotedText(p.ID))
	}
	b.WriteString("\n")
	emitArchitectureAssertion(&b, m.Architecture)

	b.WriteString("int main() {\n")
	emitStringMember(&b, "schemaVersion", strconv.Itoa(SchemaVersion), false, true)
	emitStringMember(&b, "sourceId", m.SourceID, true, false)
	emitStringMember(&b, "sdkVersion", m.SDKVersion, true, false)
	emitStringMember(&b, "profile", m.Profile, true, false)
	b.WriteString("  std::fputs(\"  \\\"architecture\\\":\", stdout); abi_json_string(abi_compiled_architecture); std::fputs(\",\\n\", stdout);\n")
	emitStringMember(&b, "manifestSha256", manifestHash, true, false)
	b.WriteString("  std::fputs(\"  \\\"compiler\\\":{\\\"family\\\":\", stdout); abi_json_string(abi_compiler_family); std::fputs(\",\\\"version\\\":\", stdout); abi_json_string(abi_compiler_version); std::fputs(\"},\\n\", stdout);\n")

	emitRecords(&b, m.Records)
	emitValues(&b, m.Values)
	emitGUIDs(&b, m.GUIDs)
	emitBitFields(&b, m.BitFields)
	emitFunctions(&b, m.Functions)
	emitVTables(&b, m.VTables)
	emitConditions(&b, m.Conditions)
	b.WriteString("  std::fputs(\"}\\n\", stdout);\n  return 0;\n}\n")
	return b.Bytes(), nil
}

func emitArchitectureAssertion(b *bytes.Buffer, architecture string) {
	expression := map[string]string{
		"386":     "defined(_M_IX86)",
		"amd64":   "defined(_M_X64) && !defined(_M_ARM64EC)",
		"arm64":   "defined(_M_ARM64) && !defined(_M_ARM64EC)",
		"arm64ec": "defined(_M_ARM64EC)",
	}[architecture]
	fmt.Fprintf(b, "#if !(%s)\n#error Probe target does not match manifest architecture %s.\n#endif\n\n", expression, architecture)
}

func emitStringMember(b *bytes.Buffer, key, value string, quoted, rawNumber bool) {
	if rawNumber {
		fmt.Fprintf(b, "  std::fputs(\"{\\n  \\\"%s\\\":%s,\\n\", stdout);\n", key, value)
		return
	}
	prefix := "  "
	if quoted {
		prefix = "  "
	}
	fmt.Fprintf(b, "  std::fputs(\"%s\\\"%s\\\":\", stdout); abi_json_string(%s); std::fputs(\",\\n\", stdout);\n", prefix, key, cppString(value))
}

func emitRecords(b *bytes.Buffer, probes []RecordProbe) {
	b.WriteString("  std::fputs(\"  \\\"records\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		fmt.Fprintf(b, "  std::printf(\",\\\"kind\\\":\\\"%s\\\",\\\"size\\\":%%llu,\\\"alignment\\\":%%llu,\\\"fields\\\":[\", static_cast<unsigned long long>(sizeof(%s)), static_cast<unsigned long long>(alignof(%s)));\n", p.Kind, p.NativeName, p.NativeName)
		for j, f := range p.Fields {
			if j > 0 {
				b.WriteString("  std::putchar(',');\n")
			}
			b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(f.ID) + ");\n")
			b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(f.NativeName) + ");\n")
			fmt.Fprintf(b, "  std::printf(\",\\\"offset\\\":%%llu}\", static_cast<unsigned long long>(offsetof(%s, %s)));\n", p.NativeName, f.NativeName)
		}
		b.WriteString("  std::fputs(\"]}\", stdout);\n")
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitValues(b *bytes.Buffer, probes []ValueProbe) {
	b.WriteString("  std::fputs(\"  \\\"values\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		if p.Unsigned {
			fmt.Fprintf(b, "  std::printf(\",\\\"value\\\":\\\"%%llu\\\"}\", static_cast<unsigned long long>(%s));\n", p.Expression)
		} else {
			fmt.Fprintf(b, "  std::printf(\",\\\"value\\\":\\\"%%lld\\\"}\", static_cast<long long>(%s));\n", p.Expression)
		}
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitGUIDs(b *bytes.Buffer, probes []GUIDProbe) {
	b.WriteString("  std::fputs(\"  \\\"guids\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		fmt.Fprintf(b, "  const GUID abi_guid_%d = %s;\n", i, p.Expression)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		fmt.Fprintf(b, "  std::fputs(\",\\\"value\\\":\\\"\", stdout); abi_print_guid(abi_guid_%d); std::fputs(\"\\\"}\", stdout);\n", i)
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitBitFields(b *bytes.Buffer, probes []BitFieldProbe) {
	b.WriteString("  std::fputs(\"  \\\"bitFields\\\":[\", stdout);\n")
	if len(probes) > 0 {
		b.WriteString("  volatile unsigned long long abi_all_bits = ~0ULL;\n")
	}
	for i, p := range probes {
		emitComma(b, i)
		fmt.Fprintf(b, "  %s abi_bitfield_%d{};\n", p.Record, i)
		fmt.Fprintf(b, "  abi_bitfield_%d.%s = static_cast<decltype(abi_bitfield_%d.%s)>(abi_all_bits);\n", i, p.Field, i, p.Field)
		fmt.Fprintf(b, "  unsigned char abi_bitfield_bytes_%d[sizeof(abi_bitfield_%d)]{};\n", i, i)
		fmt.Fprintf(b, "  std::memcpy(abi_bitfield_bytes_%d, &abi_bitfield_%d, sizeof(abi_bitfield_%d));\n", i, i, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		b.WriteString("  std::fputs(\",\\\"maskHex\\\":\\\"\", stdout);\n")
		fmt.Fprintf(b, "  for (std::size_t byte = 0; byte < sizeof(abi_bitfield_bytes_%d); ++byte) std::printf(\"%%02x\", abi_bitfield_bytes_%d[byte]);\n", i, i)
		fmt.Fprintf(b, "  std::printf(\"\\\",\\\"bitOffset\\\":%%llu,\\\"bitWidth\\\":%%llu}\", abi_first_set_bit(abi_bitfield_bytes_%d, sizeof(abi_bitfield_bytes_%d)), abi_popcount(abi_bitfield_bytes_%d, sizeof(abi_bitfield_bytes_%d)));\n", i, i, i, i)
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitFunctions(b *bytes.Buffer, probes []FunctionProbe) {
	b.WriteString("  std::fputs(\"  \\\"functions\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		b.WriteString("  std::fputs(\",\\\"typeCompatible\\\":true,\\\"callingConvention\\\":\", stdout); abi_json_string(" + cppString(p.CallingConvention) + "); std::putchar('}');\n")
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitVTables(b *bytes.Buffer, probes []VTableProbe) {
	b.WriteString("  std::fputs(\"  \\\"vtables\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"interface\\\":\", stdout); abi_json_string(" + cppString(p.Interface) + ");\n")
		b.WriteString("  std::fputs(\",\\\"method\\\":\", stdout); abi_json_string(" + cppString(p.Method) + ");\n")
		fmt.Fprintf(b, "  std::printf(\",\\\"index\\\":%%llu}\", static_cast<unsigned long long>(offsetof(%s, %s) / sizeof(void*)));\n", p.VTableType, p.Method)
	}
	b.WriteString("  std::fputs(\"],\\n\", stdout);\n")
}

func emitConditions(b *bytes.Buffer, probes []ConditionProbe) {
	b.WriteString("  std::fputs(\"  \\\"conditions\\\":[\", stdout);\n")
	for i, p := range probes {
		emitComma(b, i)
		b.WriteString("  std::fputs(\"{\\\"id\\\":\", stdout); abi_json_string(" + cppString(p.ID) + ");\n")
		b.WriteString("  std::fputs(\",\\\"nativeName\\\":\", stdout); abi_json_string(" + cppString(p.NativeName) + ");\n")
		fmt.Fprintf(b, "  std::fputs((%s) ? \",\\\"value\\\":true}\" : \",\\\"value\\\":false}\", stdout);\n", p.Expression)
	}
	b.WriteString("  std::fputs(\"]\\n\", stdout);\n")
}

func emitComma(b *bytes.Buffer, index int) {
	if index > 0 {
		b.WriteString("  std::putchar(',');\n")
	}
}

func cppString(value string) string { return strconv.QuoteToASCII(value) }

func cppQuotedText(value string) string {
	quoted := strconv.QuoteToASCII(value)
	return quoted[1 : len(quoted)-1]
}

func sortedManifest(m Manifest) Manifest {
	out := m
	out.Defines = make(map[string]string, len(m.Defines))
	for key, value := range m.Defines {
		out.Defines[key] = value
	}
	out.Includes = append([]string(nil), m.Includes...)
	out.Records = append([]RecordProbe(nil), m.Records...)
	for i := range out.Records {
		out.Records[i].Fields = append([]FieldProbe(nil), out.Records[i].Fields...)
		sort.Slice(out.Records[i].Fields, func(a, b int) bool { return out.Records[i].Fields[a].ID < out.Records[i].Fields[b].ID })
	}
	out.Values = append([]ValueProbe(nil), m.Values...)
	out.GUIDs = append([]GUIDProbe(nil), m.GUIDs...)
	out.BitFields = append([]BitFieldProbe(nil), m.BitFields...)
	out.Functions = append([]FunctionProbe(nil), m.Functions...)
	out.VTables = append([]VTableProbe(nil), m.VTables...)
	out.Conditions = append([]ConditionProbe(nil), m.Conditions...)
	sort.Slice(out.Records, func(i, j int) bool { return out.Records[i].ID < out.Records[j].ID })
	sort.Slice(out.Values, func(i, j int) bool { return out.Values[i].ID < out.Values[j].ID })
	sort.Slice(out.GUIDs, func(i, j int) bool { return out.GUIDs[i].ID < out.GUIDs[j].ID })
	sort.Slice(out.BitFields, func(i, j int) bool { return out.BitFields[i].ID < out.BitFields[j].ID })
	sort.Slice(out.Functions, func(i, j int) bool { return out.Functions[i].ID < out.Functions[j].ID })
	sort.Slice(out.VTables, func(i, j int) bool { return out.VTables[i].ID < out.VTables[j].ID })
	sort.Slice(out.Conditions, func(i, j int) bool { return out.Conditions[i].ID < out.Conditions[j].ID })
	return out
}
