// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 725a59e35bf0b734c1f185987b378cef530f0875f5b703eaaf1b40e8c8279a8b

package kernel32

// FunctionProjection records the ABI backend selected for one function.
type FunctionProjection struct {
	NativeName   string
	Backend      string
	SetLastError bool
	Optional     bool
	Reason       string
}

// SliceFunctionInventory is sorted by native name.
var SliceFunctionInventory = [...]FunctionProjection{
	{NativeName: "CloseHandle", Backend: "purego-syscall", SetLastError: true, Reason: "integer/pointer ABI"},
	{NativeName: "EnumSystemLocalesEx", Backend: "purego-syscall", SetLastError: true, Reason: "raw callback pointer; Go callback construction is not projected"},
	{NativeName: "GetCurrentProcessId", Backend: "purego-syscall", Reason: "zero-argument integer return"},
	{NativeName: "GetCurrentThreadId", Backend: "purego-syscall", Reason: "zero-argument integer return"},
	{NativeName: "GetModuleHandleW", Backend: "purego-syscall", SetLastError: true, Reason: "integer/pointer ABI"},
	{NativeName: "GetSystemTime", Backend: "purego-syscall", Reason: "pointer-only argument"},
	{NativeName: "GetSystemTimePreciseAsFileTime", Backend: "purego-syscall", Optional: true, Reason: "optional pointer-only API"},
	{NativeName: "QueryPerformanceCounter", Backend: "purego-syscall", SetLastError: true, Reason: "pointer-only argument"},
	{NativeName: "VirtualAlloc", Backend: "purego-syscall", SetLastError: true, Reason: "integer/pointer ABI"},
	{NativeName: "VirtualFree", Backend: "purego-syscall", SetLastError: true, Reason: "integer/pointer ABI"},
}
