// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 725a59e35bf0b734c1f185987b378cef530f0875f5b703eaaf1b40e8c8279a8b

package kernel32

const (
	MEM_COMMIT  uint32 = 0x00001000
	MEM_RESERVE uint32 = 0x00002000
	MEM_RELEASE uint32 = 0x00008000

	PAGE_READWRITE uint32 = 0x04

	LOCALE_ALL uint32 = 0
)
