//go:build windows && (amd64 || arm64)

// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata + Windows SDK ABI probe
// Source-Version: 71.0.26-preview / 10.0.26100.0
// Manifest-SHA256: 725a59e35bf0b734c1f185987b378cef530f0875f5b703eaaf1b40e8c8279a8b

package kernel32

import (
	"unsafe"

	"github.com/zzuf/GoWin-AFO/bindings/win32/foundation"
	"github.com/zzuf/GoWin-AFO/runtime/winabi"
)

func queryPerformanceCounterNative(value *foundation.LARGE_INTEGER) (winabi.CallResult, error) {
	return procQueryPerformanceCounter.TryCall(uintptr(unsafe.Pointer(value)))
}
