//go:build windows

// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata
// Source-Version: 71.0.26-preview
// Manifest-SHA256: 725a59e35bf0b734c1f185987b378cef530f0875f5b703eaaf1b40e8c8279a8b

package kernel32

import (
	"runtime"
	"unsafe"

	"github.com/zzuf/GoWin-AFO/bindings/win32/foundation"
	"github.com/zzuf/GoWin-AFO/runtime/winabi"
)

var (
	kernel32DLL = winabi.MustSystemDLL("kernel32.dll")

	procGetCurrentProcessID            = kernel32DLL.MustProc("GetCurrentProcessId")
	procGetCurrentThreadID             = kernel32DLL.MustProc("GetCurrentThreadId")
	procQueryPerformanceCounter        = kernel32DLL.MustProc("QueryPerformanceCounter")
	procGetSystemTime                  = kernel32DLL.MustProc("GetSystemTime")
	procVirtualAlloc                   = kernel32DLL.MustProc("VirtualAlloc")
	procVirtualFree                    = kernel32DLL.MustProc("VirtualFree")
	procCloseHandle                    = kernel32DLL.MustProc("CloseHandle")
	procGetModuleHandleW               = kernel32DLL.MustProc("GetModuleHandleW")
	procEnumSystemLocalesEx            = kernel32DLL.MustProc("EnumSystemLocalesEx")
	procGetSystemTimePreciseAsFileTime = kernel32DLL.MustProc("GetSystemTimePreciseAsFileTime")
)

func resolutionLastError(err error) winabi.LastError {
	if err == nil {
		return winabi.ERROR_SUCCESS
	}
	return winabi.ERROR_PROC_NOT_FOUND
}

// GetCurrentProcessId returns the caller's native process identifier.
func GetCurrentProcessId() uint32 {
	call, err := procGetCurrentProcessID.TryCall()
	if err != nil {
		return 0
	}
	return uint32(call.R1)
}

// GetCurrentThreadId returns the current native thread identifier.
func GetCurrentThreadId() uint32 {
	call, err := procGetCurrentThreadID.TryCall()
	if err != nil {
		return 0
	}
	return uint32(call.R1)
}

// QueryPerformanceCounter preserves BOOL and the captured last-error value.
// The last-error value is meaningful only when the BOOL result is FALSE.
func QueryPerformanceCounter(value *foundation.LARGE_INTEGER) (foundation.BOOL, winabi.LastError) {
	call, err := queryPerformanceCounterNative(value)
	runtime.KeepAlive(value)
	if err != nil {
		return foundation.FALSE, resolutionLastError(err)
	}
	return foundation.BOOL(int32(call.R1)), call.LastError
}

// GetSystemTime writes the current UTC system time.
func GetSystemTime(value *foundation.SYSTEMTIME) {
	_, _ = procGetSystemTime.TryCall(uintptr(unsafe.Pointer(value)))
	runtime.KeepAlive(value)
}

// VirtualAlloc preserves the native pointer result and SetLastError snapshot.
func VirtualAlloc(address unsafe.Pointer, size foundation.SIZE_T, allocationType, protect uint32) (unsafe.Pointer, winabi.LastError) {
	call, err := procVirtualAlloc.TryCall(uintptr(address), uintptr(size), uintptr(allocationType), uintptr(protect))
	if err != nil {
		return nil, resolutionLastError(err)
	}
	return winabi.UnsafePointerFromUintptr(call.R1), call.LastError
}

// VirtualFree preserves native BOOL and SetLastError semantics.
func VirtualFree(address unsafe.Pointer, size foundation.SIZE_T, freeType uint32) (foundation.BOOL, winabi.LastError) {
	call, err := procVirtualFree.TryCall(uintptr(address), uintptr(size), uintptr(freeType))
	if err != nil {
		return foundation.FALSE, resolutionLastError(err)
	}
	return foundation.BOOL(int32(call.R1)), call.LastError
}

// CloseHandle preserves native BOOL and SetLastError semantics.
func CloseHandle(handle foundation.HANDLE) (foundation.BOOL, winabi.LastError) {
	call, err := procCloseHandle.TryCall(uintptr(handle))
	if err != nil {
		return foundation.FALSE, resolutionLastError(err)
	}
	return foundation.BOOL(int32(call.R1)), call.LastError
}

// GetModuleHandleW accepts a borrowed NUL-terminated UTF-16 module name. A nil
// pointer requests the executable module. The caller controls pointer lifetime.
func GetModuleHandleW(name foundation.PCWSTR) (foundation.HMODULE, winabi.LastError) {
	call, err := procGetModuleHandleW.TryCall(uintptr(unsafe.Pointer(name)))
	runtime.KeepAlive(name)
	if err != nil {
		return 0, resolutionLastError(err)
	}
	return foundation.HMODULE(call.R1), call.LastError
}

// EnumSystemLocalesEx invokes a raw native callback address. This function does
// not manufacture a callback from a Go closure.
func EnumSystemLocalesEx(callback LOCALE_ENUMPROCEX, flags uint32, parameter uintptr, reserved unsafe.Pointer) (foundation.BOOL, winabi.LastError) {
	call, err := procEnumSystemLocalesEx.TryCall(uintptr(callback), uintptr(flags), parameter, uintptr(reserved))
	runtime.KeepAlive(reserved)
	if err != nil {
		return foundation.FALSE, resolutionLastError(err)
	}
	return foundation.BOOL(int32(call.R1)), call.LastError
}

// IsGetSystemTimePreciseAsFileTimeAvailable resolves the optional export.
func IsGetSystemTimePreciseAsFileTimeAvailable() bool {
	return procGetSystemTimePreciseAsFileTime.Available()
}

// GetSystemTimePreciseAsFileTime invokes the optional API when present and
// reports false without touching value when the export cannot be resolved.
func GetSystemTimePreciseAsFileTime(value *foundation.FILETIME) bool {
	if !IsGetSystemTimePreciseAsFileTimeAvailable() {
		return false
	}
	_, err := procGetSystemTimePreciseAsFileTime.TryCall(uintptr(unsafe.Pointer(value)))
	runtime.KeepAlive(value)
	return err == nil
}
