//go:build windows && 386

// Code generated by winapigen v0.1.0; DO NOT EDIT.
// Source: Microsoft.Windows.SDK.Win32Metadata + Windows SDK ABI probe
// Source-Version: 71.0.26-preview / 10.0.26100.0
// Manifest-SHA256: 725a59e35bf0b734c1f185987b378cef530f0875f5b703eaaf1b40e8c8279a8b

package kernel32

import (
	"encoding/binary"
	"runtime"
	"unsafe"

	"go-windows-api.local/bindings/win32/foundation"
	"go-windows-api.local/runtime/winabi"
)

// queryPerformanceCounterNative compensates for an ABI fact Go/386 cannot
// encode in a type: MSVC aligns LARGE_INTEGER to 8 while Go aligns int64 to 4.
func queryPerformanceCounterNative(value *foundation.LARGE_INTEGER) (winabi.CallResult, error) {
	if value == nil {
		return procQueryPerformanceCounter.TryCall(0)
	}
	var scratch [15]byte
	base := uintptr(unsafe.Pointer(&scratch[0]))
	aligned := (base + 7) &^ uintptr(7)
	call, err := procQueryPerformanceCounter.TryCall(aligned)
	if err == nil && call.R1 != 0 {
		bytes := unsafe.Slice((*byte)(winabi.UnsafePointerFromUintptr(aligned)), 8)
		value.SetInt64(int64(binary.LittleEndian.Uint64(bytes)))
	}
	runtime.KeepAlive(&scratch)
	runtime.KeepAlive(value)
	return call, err
}
