package slice

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Write stages every output before changing any destination. It preserves
// handwritten files beside the slice and rolls back changed files on failure.
func Write(root string, tree Tree) error {
	if err := ValidateDestinations(root, tree); err != nil {
		return err
	}
	paths := sortedPaths(tree.Files)
	// Keep the manifest last so an interrupted write never advertises new
	// artifact hashes before the corresponding files exist.
	for i, path := range paths {
		if path == "bindings/slice.manifest.json" {
			paths = append(append(paths[:i:i], paths[i+1:]...), path)
			break
		}
	}
	stageParent := filepath.Join(root, "bindings")
	if err := os.MkdirAll(stageParent, 0o755); err != nil {
		return err
	}
	stage, err := os.MkdirTemp(stageParent, ".slicegen-")
	if err != nil {
		return err
	}
	cleanup := true
	defer func() {
		if cleanup {
			_ = os.RemoveAll(stage)
		}
	}()
	for i, path := range paths {
		file := filepath.Join(stage, "new", fmt.Sprintf("%02d", i))
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(file, tree.Files[path], 0o644); err != nil {
			return err
		}
	}
	type replaced struct {
		dest, backup string
		installed    bool
	}
	var changed []replaced
	rollback := func(cause error) error {
		var undoErrors []error
		for i := len(changed) - 1; i >= 0; i-- {
			item := changed[i]
			if item.installed {
				if err := os.Remove(item.dest); err != nil {
					undoErrors = append(undoErrors, fmt.Errorf("remove %s: %w", item.dest, err))
					continue
				}
			}
			if item.backup != "" {
				if err := os.Rename(item.backup, item.dest); err != nil {
					undoErrors = append(undoErrors, fmt.Errorf("restore %s from %s: %w", item.dest, item.backup, err))
				}
			}
		}
		if len(undoErrors) != 0 {
			cleanup = false // Keep the backups for manual recovery.
		}
		return errors.Join(append([]error{cause}, undoErrors...)...)
	}
	for i, path := range paths {
		dest := filepath.Join(root, filepath.FromSlash(path))
		data := tree.Files[path]
		if old, err := os.ReadFile(dest); err == nil && bytes.Equal(old, data) {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return rollback(err)
		}
		backup := ""
		if _, err := os.Stat(dest); err == nil {
			backup = filepath.Join(stage, "old", fmt.Sprintf("%02d", i))
			if err := os.MkdirAll(filepath.Dir(backup), 0o755); err != nil {
				return rollback(err)
			}
			if err := os.Rename(dest, backup); err != nil {
				return rollback(err)
			}
		} else if !os.IsNotExist(err) {
			return rollback(err)
		}
		changed = append(changed, replaced{dest: dest, backup: backup})
		newFile := filepath.Join(stage, "new", fmt.Sprintf("%02d", i))
		if err := os.Rename(newFile, dest); err != nil {
			return rollback(err)
		}
		changed[len(changed)-1].installed = true
	}
	return nil
}

// ValidateDestinations rejects collisions with handwritten files and unknown
// manifests at the exact paths managed by the reviewed slice.
func ValidateDestinations(root string, tree Tree) error {
	if len(tree.Files) != len(artifactPaths)+1 {
		return fmt.Errorf("slice tree has %d files, want %d", len(tree.Files), len(artifactPaths)+1)
	}
	allowed := map[string]bool{"bindings/slice.manifest.json": true}
	for _, path := range artifactPaths {
		allowed[path] = true
	}
	paths := sortedPaths(tree.Files)
	for _, path := range paths {
		if !allowed[path] {
			return fmt.Errorf("unexpected slice path %q", path)
		}
		dest := filepath.Join(root, filepath.FromSlash(path))
		if info, err := os.Lstat(dest); err == nil {
			if !info.Mode().IsRegular() {
				return fmt.Errorf("slice destination is not a regular file: %s", dest)
			}
			data, err := os.ReadFile(dest)
			if err != nil {
				return err
			}
			if path == "bindings/slice.manifest.json" {
				var existing manifest
				if err := json.Unmarshal(data, &existing); err != nil || existing.SchemaVersion != 1 || !strings.HasPrefix(existing.Generator, "winapigen v") || len(existing.Artifacts) == 0 {
					return fmt.Errorf("refusing to replace unrecognized slice manifest %s", dest)
				}
			} else if !bytes.HasPrefix(data, []byte("// Code generated by winapigen ")) && !(bytes.HasPrefix(data, []byte("//go:build ")) && bytes.Contains(data[:min(len(data), 256)], []byte("// Code generated by winapigen "))) {
				return fmt.Errorf("refusing to replace handwritten file at slice path %s", dest)
			}
		} else if !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}
