// Code generated by winapigen 0.1.0; DO NOT EDIT.
// SPDX-License-Identifier: Apache-2.0
// Licensing and upstream notices: docs/licensing.md and NOTICE.
// Inputs: fixture-e2e-v1@1.0.0
// Manifest-SHA256: 05ae35fde5e7341dc2d55ae8148cbff5e83f11aacb41b13c644d1d08886e6341

package foundation

// WNDENUMPROC is a raw callback address. Its owner must keep the callback alive and
// prevent invocation after release.
type WNDENUMPROC uintptr
