// Code generated by go-windows-api ABI oracle. DO NOT EDIT.
// Generator: abi-oracle 0.1.0; source: vertical-slice-sdk-10.0.26100; SDK: 10.0.26100.0; manifest SHA-256: 043c280224221fe8299d38dd2c2c3a23ae998e0d5e6779039c54d487980ce312

#ifndef INITGUID
#define INITGUID 1
#endif
#ifndef NTDDI_VERSION
#define NTDDI_VERSION 0x0A00000C
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN 1
#endif
#ifndef WINVER
#define WINVER 0x0A00
#endif
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0A00
#endif
#ifndef CINTERFACE
#define CINTERFACE
#endif
#ifndef COBJMACROS
#define COBJMACROS
#endif

#include <windows.h>
#include <unknwn.h>
#include <d3d9types.h>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <type_traits>

#define ABI_STRINGIFY_INNER(value) #value
#define ABI_STRINGIFY(value) ABI_STRINGIFY_INNER(value)

#if defined(__clang__)
static constexpr const char* abi_compiler_family = "clang-cl";
static constexpr const char* abi_compiler_version = ABI_STRINGIFY(__clang_major__) "." ABI_STRINGIFY(__clang_minor__) "." ABI_STRINGIFY(__clang_patchlevel__);
#elif defined(_MSC_VER)
static constexpr const char* abi_compiler_family = "msvc";
static constexpr const char* abi_compiler_version = ABI_STRINGIFY(_MSC_FULL_VER);
#else
#error Unsupported compiler: use MSVC or clang-cl.
#endif

#if defined(_M_ARM64EC)
static constexpr const char* abi_compiled_architecture = "arm64ec";
#elif defined(_M_IX86)
static constexpr const char* abi_compiled_architecture = "386";
#elif defined(_M_X64)
static constexpr const char* abi_compiled_architecture = "amd64";
#elif defined(_M_ARM64)
static constexpr const char* abi_compiled_architecture = "arm64";
#else
#error Unsupported Windows architecture.
#endif

static void abi_json_string(const char* value) {
  std::putchar('"');
  for (const unsigned char* p = reinterpret_cast<const unsigned char*>(value); *p; ++p) {
    switch (*p) {
      case '"': std::fputs("\\\"", stdout); break;
      case '\\': std::fputs("\\\\", stdout); break;
      case '\b': std::fputs("\\b", stdout); break;
      case '\f': std::fputs("\\f", stdout); break;
      case '\n': std::fputs("\\n", stdout); break;
      case '\r': std::fputs("\\r", stdout); break;
      case '\t': std::fputs("\\t", stdout); break;
      default:
        if (*p < 0x20) std::printf("\\u%04x", static_cast<unsigned>(*p));
        else std::putchar(*p);
    }
  }
  std::putchar('"');
}

static void abi_print_guid(const GUID& value) {
  std::printf("%08lx-%04hx-%04hx-%02hhx%02hhx-%02hhx%02hhx%02hhx%02hhx%02hhx%02hhx",
      static_cast<unsigned long>(value.Data1), value.Data2, value.Data3,
      value.Data4[0], value.Data4[1], value.Data4[2], value.Data4[3],
      value.Data4[4], value.Data4[5], value.Data4[6], value.Data4[7]);
}

static unsigned long long abi_first_set_bit(const unsigned char* bytes, std::size_t size) {
  for (std::size_t byte = 0; byte < size; ++byte) {
    for (unsigned bit = 0; bit < 8; ++bit) {
      if ((bytes[byte] & (1u << bit)) != 0) return static_cast<unsigned long long>(byte * 8 + bit);
    }
  }
  return static_cast<unsigned long long>(size * 8);
}

static unsigned long long abi_popcount(const unsigned char* bytes, std::size_t size) {
  unsigned long long count = 0;
  for (std::size_t byte = 0; byte < size; ++byte) {
    unsigned value = bytes[byte];
    while (value != 0) { count += value & 1u; value >>= 1; }
  }
  return count;
}

using abi_expected_function_0 = DWORD (WINAPI *)(void);
static_assert(std::is_same_v<decltype(&::GetCurrentProcessId), abi_expected_function_0>, "ABI function pointer mismatch: function.GetCurrentProcessId");
using abi_expected_function_1 = BOOL (WINAPI *)(LARGE_INTEGER*);
static_assert(std::is_same_v<decltype(&::QueryPerformanceCounter), abi_expected_function_1>, "ABI function pointer mismatch: function.QueryPerformanceCounter");

#if !(defined(_M_X64) && !defined(_M_ARM64EC))
#error Probe target does not match manifest architecture amd64.
#endif

int main() {
  std::fputs("{\n  \"schemaVersion\":1,\n", stdout);
  std::fputs("  \"sourceId\":", stdout); abi_json_string("vertical-slice-sdk-10.0.26100"); std::fputs(",\n", stdout);
  std::fputs("  \"sdkVersion\":", stdout); abi_json_string("10.0.26100.0"); std::fputs(",\n", stdout);
  std::fputs("  \"profile\":", stdout); abi_json_string("windows-desktop"); std::fputs(",\n", stdout);
  std::fputs("  \"architecture\":", stdout); abi_json_string(abi_compiled_architecture); std::fputs(",\n", stdout);
  std::fputs("  \"manifestSha256\":", stdout); abi_json_string("043c280224221fe8299d38dd2c2c3a23ae998e0d5e6779039c54d487980ce312"); std::fputs(",\n", stdout);
  std::fputs("  \"compiler\":{\"family\":", stdout); abi_json_string(abi_compiler_family); std::fputs(",\"version\":", stdout); abi_json_string(abi_compiler_version); std::fputs("},\n", stdout);
  std::fputs("  \"records\":[", stdout);
  std::fputs("{\"id\":", stdout); abi_json_string("record.FILETIME");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("FILETIME");
  std::printf(",\"kind\":\"struct\",\"size\":%llu,\"alignment\":%llu,\"fields\":[", static_cast<unsigned long long>(sizeof(FILETIME)), static_cast<unsigned long long>(alignof(FILETIME)));
  std::fputs("{\"id\":", stdout); abi_json_string("dwHighDateTime");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("dwHighDateTime");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(FILETIME, dwHighDateTime)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("dwLowDateTime");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("dwLowDateTime");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(FILETIME, dwLowDateTime)));
  std::fputs("]}", stdout);
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("record.GUID");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("GUID");
  std::printf(",\"kind\":\"struct\",\"size\":%llu,\"alignment\":%llu,\"fields\":[", static_cast<unsigned long long>(sizeof(GUID)), static_cast<unsigned long long>(alignof(GUID)));
  std::fputs("{\"id\":", stdout); abi_json_string("Data1");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Data1");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(GUID, Data1)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("Data2");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Data2");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(GUID, Data2)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("Data3");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Data3");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(GUID, Data3)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("Data4");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Data4");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(GUID, Data4)));
  std::fputs("]}", stdout);
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("record.LARGE_INTEGER");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("LARGE_INTEGER");
  std::printf(",\"kind\":\"union\",\"size\":%llu,\"alignment\":%llu,\"fields\":[", static_cast<unsigned long long>(sizeof(LARGE_INTEGER)), static_cast<unsigned long long>(alignof(LARGE_INTEGER)));
  std::fputs("{\"id\":", stdout); abi_json_string("HighPart");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("HighPart");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(LARGE_INTEGER, HighPart)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("LowPart");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("LowPart");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(LARGE_INTEGER, LowPart)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("QuadPart");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("QuadPart");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(LARGE_INTEGER, QuadPart)));
  std::fputs("]}", stdout);
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("record.OVERLAPPED");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("OVERLAPPED");
  std::printf(",\"kind\":\"struct\",\"size\":%llu,\"alignment\":%llu,\"fields\":[", static_cast<unsigned long long>(sizeof(OVERLAPPED)), static_cast<unsigned long long>(alignof(OVERLAPPED)));
  std::fputs("{\"id\":", stdout); abi_json_string("Internal");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Internal");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(OVERLAPPED, Internal)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("InternalHigh");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("InternalHigh");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(OVERLAPPED, InternalHigh)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("Offset");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("Offset");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(OVERLAPPED, Offset)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("OffsetHigh");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("OffsetHigh");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(OVERLAPPED, OffsetHigh)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("hEvent");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("hEvent");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(OVERLAPPED, hEvent)));
  std::fputs("]}", stdout);
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("record.SYSTEMTIME");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("SYSTEMTIME");
  std::printf(",\"kind\":\"struct\",\"size\":%llu,\"alignment\":%llu,\"fields\":[", static_cast<unsigned long long>(sizeof(SYSTEMTIME)), static_cast<unsigned long long>(alignof(SYSTEMTIME)));
  std::fputs("{\"id\":", stdout); abi_json_string("wDay");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wDay");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wDay)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wDayOfWeek");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wDayOfWeek");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wDayOfWeek)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wHour");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wHour");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wHour)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wMilliseconds");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wMilliseconds");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wMilliseconds)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wMinute");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wMinute");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wMinute)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wMonth");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wMonth");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wMonth)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wSecond");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wSecond");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wSecond)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("wYear");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("wYear");
  std::printf(",\"offset\":%llu}", static_cast<unsigned long long>(offsetof(SYSTEMTIME, wYear)));
  std::fputs("]}", stdout);
  std::fputs("],\n", stdout);
  std::fputs("  \"values\":[", stdout);
  std::fputs("{\"id\":", stdout); abi_json_string("constant.PAGE_READWRITE");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("PAGE_READWRITE");
  std::printf(",\"value\":\"%llu\"}", static_cast<unsigned long long>(PAGE_READWRITE));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("constant.WAIT_TIMEOUT");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("WAIT_TIMEOUT");
  std::printf(",\"value\":\"%llu\"}", static_cast<unsigned long long>(WAIT_TIMEOUT));
  std::fputs("],\n", stdout);
  std::fputs("  \"guids\":[", stdout);
  const GUID abi_guid_0 = IID_IUnknown;
  std::fputs("{\"id\":", stdout); abi_json_string("guid.IID_IUnknown");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("IID_IUnknown");
  std::fputs(",\"value\":\"", stdout); abi_print_guid(abi_guid_0); std::fputs("\"}", stdout);
  std::fputs("],\n", stdout);
  std::fputs("  \"bitFields\":[", stdout);
  volatile unsigned long long abi_all_bits = ~0ULL;
  D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS abi_bitfield_0{};
  abi_bitfield_0.ProtectionEnabled = static_cast<decltype(abi_bitfield_0.ProtectionEnabled)>(abi_all_bits);
  unsigned char abi_bitfield_bytes_0[sizeof(abi_bitfield_0)]{};
  std::memcpy(abi_bitfield_bytes_0, &abi_bitfield_0, sizeof(abi_bitfield_0));
  std::fputs("{\"id\":", stdout); abi_json_string("bitfield.D3DAUTHENTICATEDCHANNEL_PROTECTION_FLAGS.ProtectionEnabled");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("ProtectionEnabled");
  std::fputs(",\"maskHex\":\"", stdout);
  for (std::size_t byte = 0; byte < sizeof(abi_bitfield_bytes_0); ++byte) std::printf("%02x", abi_bitfield_bytes_0[byte]);
  std::printf("\",\"bitOffset\":%llu,\"bitWidth\":%llu}", abi_first_set_bit(abi_bitfield_bytes_0, sizeof(abi_bitfield_bytes_0)), abi_popcount(abi_bitfield_bytes_0, sizeof(abi_bitfield_bytes_0)));
  std::fputs("],\n", stdout);
  std::fputs("  \"functions\":[", stdout);
  std::fputs("{\"id\":", stdout); abi_json_string("function.GetCurrentProcessId");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("GetCurrentProcessId");
  std::fputs(",\"typeCompatible\":true,\"callingConvention\":", stdout); abi_json_string("WINAPI"); std::putchar('}');
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("function.QueryPerformanceCounter");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("QueryPerformanceCounter");
  std::fputs(",\"typeCompatible\":true,\"callingConvention\":", stdout); abi_json_string("WINAPI"); std::putchar('}');
  std::fputs("],\n", stdout);
  std::fputs("  \"vtables\":[", stdout);
  std::fputs("{\"id\":", stdout); abi_json_string("vtable.IUnknown.AddRef");
  std::fputs(",\"interface\":", stdout); abi_json_string("IUnknown");
  std::fputs(",\"method\":", stdout); abi_json_string("AddRef");
  std::printf(",\"index\":%llu}", static_cast<unsigned long long>(offsetof(IUnknownVtbl, AddRef) / sizeof(void*)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("vtable.IUnknown.QueryInterface");
  std::fputs(",\"interface\":", stdout); abi_json_string("IUnknown");
  std::fputs(",\"method\":", stdout); abi_json_string("QueryInterface");
  std::printf(",\"index\":%llu}", static_cast<unsigned long long>(offsetof(IUnknownVtbl, QueryInterface) / sizeof(void*)));
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("vtable.IUnknown.Release");
  std::fputs(",\"interface\":", stdout); abi_json_string("IUnknown");
  std::fputs(",\"method\":", stdout); abi_json_string("Release");
  std::printf(",\"index\":%llu}", static_cast<unsigned long long>(offsetof(IUnknownVtbl, Release) / sizeof(void*)));
  std::fputs("],\n", stdout);
  std::fputs("  \"conditions\":[", stdout);
  std::fputs("{\"id\":", stdout); abi_json_string("condition.pointer64");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("sizeof(void*) == 8");
  std::fputs((sizeof(void*) == 8) ? ",\"value\":true}" : ",\"value\":false}", stdout);
  std::putchar(',');
  std::fputs("{\"id\":", stdout); abi_json_string("condition.win10");
  std::fputs(",\"nativeName\":", stdout); abi_json_string("_WIN32_WINNT >= 0x0A00");
  std::fputs((_WIN32_WINNT >= 0x0A00) ? ",\"value\":true}" : ",\"value\":false}", stdout);
  std::fputs("]\n", stdout);
  std::fputs("}\n", stdout);
  return 0;
}
